apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: devops-test-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devops-nginx-test-app
  template:
    metadata:
      labels:
        app: devops-nginx-test-app
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
