apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: devops-test-namespace
spec:
  selector:
    app: devops-nginx-test-app
  ports:
  - name: http
    port: 80
    targetPort: 80
  type: ClusterIP
